# Generated by Django 5.2.3 on 2025-06-30 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=100, unique=True, verbose_name='Consignee No.')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('consignee_address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date_added', 'consignee_name', 'consignee_address'],
            },
        ),
        migrations.CreateModel(
            name='Consigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consigner_name', models.CharField(max_length=100, unique=True, verbose_name='Consigner No.')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('consigner_address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date_added', 'consigner_name', 'consigner_address'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True, verbose_name='Location Name')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
            options={
                'ordering': ['-date_added', 'location_name'],
            },
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnid', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=255)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100, unique=True, verbose_name='Vehicle No.')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
            options={
                'ordering': ['-date_added', 'vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('CNID', models.AutoField(primary_key=True, serialize=False)),
                ('Cn_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Booking_Date', models.DateField(default=django.utils.timezone.now)),
                ('Loading_Date', models.DateField()),
                ('Unloading_Date', models.DateField()),
                ('Truck_Freight', models.IntegerField()),
                ('Advance_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Balance_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Innam', models.IntegerField()),
                ('Extra_TF', models.IntegerField()),
                ('total_fare', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consignee')),
                ('consigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consigner')),
                ('To_Location', models.ForeignKey(db_column='To_Location', on_delete=django.db.models.deletion.CASCADE, related_name='consignments_to', to='accounts.location')),
                ('from_location', models.ForeignKey(db_column='from_location', on_delete=django.db.models.deletion.CASCADE, related_name='consignments_from', to='accounts.location')),
                ('Vehicle_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('GI_ID', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(blank=True, choices=[('kg', 'kg'), ('carat', 'carat')], max_length=255, null=True, verbose_name='Unit')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity (Kg)')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate')),
                ('gi_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='GI Amount')),
                ('party_payment', models.DateField(blank=True, null=True, verbose_name='Party Payment Date')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_items', to='accounts.consignment')),
                ('from_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gi_from', to='accounts.consignee', verbose_name='from_Party')),
                ('to_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gi_to', to='accounts.consignee', verbose_name='to_Party')),
            ],
            options={
                'ordering': ['GI_ID'],
            },
        ),
    ]
