# Generated by Django 5.2.3 on 2025-07-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='To_Location',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='from_location',
        ),
        migrations.AddField(
            model_name='consignment',
            name='from_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_party', to='accounts.consigner'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='to_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_party', to='accounts.consignee'),
        ),
    ]
