# Generated by Django 5.2.3 on 2025-07-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_consignment_to_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='from_party',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='to_party',
        ),
        migrations.AddField(
            model_name='consignment',
            name='To_Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_location', to='accounts.location'),
        ),
    ]
