# Generated by Django 5.2.3 on 2025-07-04 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_consignment_from_party_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='consignee',
            new_name='party',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='cnid',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='total_fare',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.consignment'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='goods_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.goodsinfo'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.CharField(choices=[('Parcha', 'Parcha'), ('Part Payment', 'Part Payment')], default='payments', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, choices=[('10kg', '10 KG'), ('15kg', '15 KG'), ('20kg', '20 KG')], max_length=255, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
