# Generated by Django 5.2.3 on 2025-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_consignee_paymentrecord_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='CNID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GI_ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
