# Generated by Django 5.2.3 on 2025-07-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_consignment_cnid_alter_goodsinfo_gi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Owner Phone'),
        ),
    ]
