# Generated by Django 5.2.3 on 2025-07-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vehicle_owner_name_vehicle_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact No.'),
        ),
    ]
