# Generated by Django 5.2.3 on 2025-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consignee_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
