# Generated by Django 5.2.3 on 2025-07-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_paymentrecord_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
