# Generated by Django 5.2.3 on 2025-07-17 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_goodsinfo_balance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol_pump_name', models.CharField(max_length=100, unique=True, verbose_name='Petrol Pump No.')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner Name')),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Owner Phone')),
                ('address', models.CharField(max_length=100)),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
            options={
                'ordering': ['-date_added', 'petrol_pump_name'],
            },
        ),
    ]
