# Generated by Django 5.2.3 on 2025-07-17 11:40

from django.db import migrations, models
import datetime  # ✅ Add this

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_petrolpump'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrolpump',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
