# Generated by Django 5.2.3 on 2025-07-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_petrolpump_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petrolpump',
            name='created_at',
        ),
    ]
