# Generated by Django 5.2.3 on 2025-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_consignment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
