# Generated by Django 5.2.3 on 2025-07-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_consignment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='created_at',
        ),
    ]
