# Generated by Django 5.2.3 on 2025-07-17 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_petrolpump_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_employee_name', models.CharField(max_length=100, unique=True, verbose_name='Staff Employee Name.')),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone No.')),
                ('address', models.CharField(max_length=100)),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_added', 'staff_employee_name'],
            },
        ),
        migrations.AlterField(
            model_name='petrolpump',
            name='petrol_pump_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Petrol Pump Name.'),
        ),
    ]
