# Generated by Django 5.2.3 on 2025-07-17 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_staffemployee_alter_petrolpump_petrol_pump_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_account_name', models.CharField(choices=[('Petrol Pump', 'Petrol Pump'), ('Staff/Employee', 'Staff/Employee')], max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
