# Generated by Django 5.2.3 on 2025-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_recordexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordexpense',
            name='payment_type',
            field=models.CharField(choices=[('Petrol Pump', 'Petrol Pump'), ('Staff/Employee', 'Staff/Employee')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordexpense',
            name='expense_account_name',
            field=models.CharField(max_length=100),
        ),
    ]
