# Generated by Django 5.2.3 on 2025-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_recordexpense_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordexpense',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='recordexpense',
            name='expense_account_name',
            field=models.CharField(choices=[('Petrol Pump', 'Petrol Pump'), ('Staff/Employee', 'Staff/Employee')], max_length=20),
        ),
    ]
