# Generated by Django 5.2.3 on 2025-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_recordexpense_expense_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
