# Generated by Django 5.2.3 on 2025-07-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_consignment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='Truck_Freight',
            new_name='Truck_Fare',
        ),
    ]
