# Generated by Django 5.2.3 on 2025-07-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_truck_freight_consignment_truck_fare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='Truck_Fare',
            new_name='Truck_Freight',
        ),
    ]
