# Generated by Django 5.2.3 on 2025-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_recordexpense_expense_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordexpense',
            name='expense_account_type',
            field=models.CharField(choices=[('Petrol Pump', 'Petrol Pump'), ('Staff/Employee', 'Staff/Employee'), ('Vehicle', 'Vehicle')], max_length=20),
        ),
    ]
