# Generated by Django 5.2.3 on 2025-07-31 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_recordexpense_expense_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordexpense',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.consignment'),
        ),
        migrations.AddField(
            model_name='recordexpense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle'),
        ),
    ]
