# Generated by Django 5.2.3 on 2025-07-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_recordexpense_consignment_recordexpense_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordexpense',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='recordexpense',
            name='vehicle',
        ),
    ]
