# Generated by Django 5.2.3 on 2025-08-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_recordexpense_consignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordexpense',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.consignment'),
        ),
    ]
