# Generated by Django 5.2.3 on 2025-08-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_recordexpense_consignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordexpense',
            name='consignment',
        ),
    ]
