# Generated by Django 5.2.3 on 2025-06-13 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 13, 8, 48, 30, 51746, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
