# Generated by Django 5.2.3 on 2025-06-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_goodsinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consignee'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='consigner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consigner'),
        ),
    ]
