# Generated by Django 5.2.3 on 2025-06-14 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_consignment_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
