# Generated by Django 5.2.3 on 2025-06-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_consignment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='goods_info',
        ),
    ]
