# Generated by Django 5.2.3 on 2025-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_consignment_goods_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='consignee_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consigner',
            name='consigner_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
