# Generated by Django 5.2.3 on 2025-06-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_consignee_consignee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='consignee_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consigner',
            name='consigner_address',
            field=models.CharField(max_length=100),
        ),
    ]
