# Generated by Django 5.1.1 on 2025-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_consignee_consignee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='goods_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
