# Generated by Django 5.1.1 on 2025-06-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_consignment_goods_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='Advance_Amount',
            new_name='advance_amount',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Balance_Amount',
            new_name='balance_amount',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Booking_Date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='CNID',
            new_name='cnid',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Extra_TF',
            new_name='extra_tf',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Innam',
            new_name='innam',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Loading_Date',
            new_name='loading_date',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='To_Location',
            new_name='to_Location',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Truck_Freight',
            new_name='truck_freight',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='Unloading_Date',
            new_name='unloading_date',
        ),
    ]
