# Generated by Django 5.1.1 on 2025-06-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_advance_amount_consignment_advance_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='advance_amount',
            new_name='Advance_Amount',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='balance_amount',
            new_name='Balance_Amount',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='booking_date',
            new_name='Booking_Date',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='cnid',
            new_name='CNID',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='extra_tf',
            new_name='Extra_TF',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='innam',
            new_name='Innam',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='loading_date',
            new_name='Loading_Date',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='to_Location',
            new_name='To_Location',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='truck_freight',
            new_name='Truck_Freight',
        ),
        migrations.RenameField(
            model_name='consignment',
            old_name='unloading_date',
            new_name='Unloading_Date',
        ),
    ]
