# Generated by Django 5.1.1 on 2025-06-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_advance_amount_consignment_advance_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='vehicle_no',
            new_name='Vehicle_No',
        ),
    ]
