# Generated by Django 5.1.1 on 2025-06-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_vehicle_no_consignment_vehicle_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='cn_no',
            new_name='Cn_No',
        ),
    ]
