# Generated by Django 5.1.1 on 2025-06-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_cn_no_consignment_cn_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='consignee',
            new_name='Consignee',
        ),
    ]
