# Generated by Django 5.1.1 on 2025-06-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_consignee_consignment_consignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='Consignee',
            new_name='consignee',
        ),
    ]
