# Generated by Django 5.1.1 on 2025-06-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_consignee_consignment_consignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='Vehicle_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle'),
        ),
    ]
