# Generated by Django 5.1.1 on 2025-06-17 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='from_party',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='From Party'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='GI Amount'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='to_party',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='To Party'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('carat', 'carat')], default='', max_length=255, verbose_name='Unit'),
        ),
    ]
