# Generated by Django 5.1.1 on 2025-06-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_goodsinfo_from_party_alter_goodsinfo_gi_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='from_party',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='From Party'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gi_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='GI Amount'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity (Kg)'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='to_party',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To Party'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('carat', 'carat')], max_length=255, null=True, verbose_name='Unit'),
        ),
    ]
