# Generated by Django 5.1.1 on 2025-06-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_goodsinfo_from_party_alter_goodsinfo_gi_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsinfo',
            name='created_at',
        ),
    ]
