# Generated by Django 5.1.1 on 2025-06-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_goodsinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
