# Generated by Django 5.1.1 on 2025-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_paymentrecord_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, choices=[('10 kg', '10 kg'), ('15 kg', '15 kg'), ('20 kg', '20 kg')], max_length=255, null=True, verbose_name='Unit'),
        ),
    ]
