# Generated by Django 5.1.1 on 2025-06-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_goodsinfo_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('carat', 'carat')], max_length=255, null=True, verbose_name='Unit'),
        ),
    ]
