# Generated by Django 5.2.3 on 2025-06-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_goodsinfo_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='goods_info',
        ),
    ]
