# Generated by Django 5.2.3 on 2025-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_consignment_goods_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='Cn_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
