# Generated by Django 5.2.3 on 2025-06-18 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_consignment_cn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
