# Generated by Django 5.2.3 on 2025-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_goodsinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='username',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='username',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(default='prajwalwarhade07@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
