# Generated by Django 5.2.3 on 2025-06-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_loginmodel_username_remove_otpmodel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='from_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gi_from', to='accounts.consignee', verbose_name='from_Party'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='to_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gi_to', to='accounts.consignee', verbose_name='to_Party'),
        ),
    ]
