# Generated by Django 5.2.3 on 2025-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_goodsinfo_paid_amount_goodsinfo_party_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paid Amount'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='party_payment',
            field=models.DateField(blank=True, null=True, verbose_name='Party Payment Date'),
        ),
    ]
