# Generated by Django 5.2.3 on 2025-07-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_goodsinfo_paid_amount_goodsinfo_party_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='To_Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_location', to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_location', to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='unit',
            field=models.CharField(blank=True, choices=[('10kg', '10 KG'), ('15kg', '15 KG'), ('20kg', '20 KG')], max_length=255, null=True, verbose_name='Unit'),
        ),
    ]
